# Generated by Django 3.2.12 on 2023-02-07 19:51

import apps.ResumeBuilder.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=apps.ResumeBuilder.models.get_file_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResumeBuilder.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
