# Generated by Django 3.2.12 on 2023-02-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0002_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='user_id',
        ),
    ]
