# Generated by Django 3.2.12 on 2023-02-08 19:19

from django.db import migrations, models
import django.db.models.deletion
import lib.functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('ResumeBuilder', '0006_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Data',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('coursework', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume_file',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=lib.functions.get_file_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
