# Generated by Django 3.2.12 on 2023-02-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0008_auto_20230208_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume_file',
        ),
    ]
