# Generated by Django 3.2.12 on 2023-02-09 06:08

from django.db import migrations, models
import django.db.models.deletion
import lib.functions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
        ('ResumeBuilder', '0009_delete_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_file',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=lib.functions.get_file_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
