# Generated by Django 3.2.12 on 2023-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0010_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_data',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume_data',
            name='extra_curricular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume_data',
            name='position_of_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
